### ISSUE TITLE
2nd row is buggy

### ISSUE THREAD

**Issue by Brokoli5191** [sosauce/CuteCalc#1]
![Screenshot_20231226-213432](https://github.com/sosauce/CuteCalc/assets/119419930/4556d35d-0182-4590-adb1-68ebdeb57797)
The 8th number when calculating is always in a second very bugged row :[
Besides that app is really cool :]
Layout looks good 👍🏿

**Comment by Brokoli5191** [comment]
Device: Samsung Galaxy a12 Android 12 one UI core. 4.1

**Comment by driftywinds** [comment]
Same issue with me

![Screenshot_2023-12-27-09-50-50-05_ffb20625144c536ab7369faffcb64309](https://github.com/sosauce/CuteCalc/assets/63164617/568a1aa5-92c2-4994-83e6-ded0fc8bc735)

**Comment by sosauce** [comment]
Hiiii! Should be fixed in v1.0.1 ! wich is avaible right now!
