### ISSUE TITLE
bad expressions cause a crash

### ISSUE THREAD

**Issue by searinminecraft** [sosauce/CuteCalc#11]
when you enter a bad math expression (for example, dividing by zero and improper math expressions), it will cause the app to crash instead of saying something like "Cannot divide by zero" or "Bad expression"

https://github.com/sosauce/CuteCalc/assets/114207889/e01a9ec0-3c1d-40c4-afc5-14a1f2ec2991

https://github.com/sosauce/CuteCalc/assets/114207889/dc1b1d50-83bb-4fe4-8758-f6f6a38a7bba

**Comment by sosauce** [comment]
Hello, i'm curently working on that, note that i am note the author of the math engine I use, wich is : https://github.com/notKamui/Keval So until the author does something about it, I need to look for a workaround :)

**Comment by sosauce** [comment]
Okay, fixed in [2.2.0](https://github.com/sosauce/CuteCalc/releases/tag/v2.2.0) Still need to find a workaround for negative numbers tho... 🤔

**Comment by adarsh1001** [comment]
Also the crash on division by 0 needs a fix.

**Comment by sosauce** [comment]
Fixed in [v2.2.1](https://github.com/sosauce/CuteCalc/releases/tag/v2.2.1)
