### ISSUE TITLE
Issue with %. 

### ISSUE THREAD

**Issue by quadroli** [sosauce/CuteCalc#15]
It shows error, a more desirable behaviour would be 89% = 0.89

Also % symbol does not show fully in potrait mode.

![Screenshot_20240119_123844](https://github.com/sosauce/CuteCalc/assets/58091631/baaea15c-5172-482c-82fc-d4a56d6c1f71)

**Comment by sosauce** [comment]
Hello, the calculator uses the % as modulo, so for example 90%2 would give 0. It isn't used to do what you are trying todo, and I can't change it as I use notKamui's Keval library so it would be up to him to change that ;),and im aware it doesn't fully show, searching how to fix 🤔

**Comment by quadroli** [comment]
Ooh, sorry. I misinterpreted what it does

**Comment by sosauce** [comment]
Ahah no worries! Math is confusing 😒

**Comment by quadroli** [comment]
Hello 👋 congrats on 2.4 👏
now, small issue, % still only mostly shows but not fully ( in potrait mode )

![Screenshot_20240126_090606](https://github.com/sosauce/CuteCalc/assets/58091631/d7d5026f-da48-4f3a-9009-bf258d4232dc)

**Comment by sosauce** [comment]
Oopsies, will fix after school ahah

**Comment by sosauce** [comment]
Was this fixed in 2.5 ?

**Comment by quadroli** [comment]
Wow bro, you've outdone yourself 🥳
It's perfect 

![Screenshot_20240128_125124](https://github.com/sosauce/CuteCalc/assets/58091631/17f90fca-63d5-451c-b274-63cdfd427702)

**Comment by quadroli** [comment]
It's a little bit  🤏 off-centre but that's fine by me ☺️
