### ISSUE TITLE
Buttons do not fully show in landscape

### ISSUE THREAD

**Issue by quadroli** [sosauce/CuteCalc#16]
The bottom buttons do not show fully. Also the button 0 seems to disappear 🤔

![Screenshot_20240119_124142](https://github.com/sosauce/CuteCalc/assets/58091631/26aeaf9f-255c-4abb-9cf7-28063b61dbfa)

**Comment by sosauce** [comment]
Oh weird, when i tested they all showed up gotta work on that ;)

**Comment by quadroli** [comment]
Nicee :)
PS: This is an amazing project!! Might even main it once its more stable :)

**Comment by quadroli** [comment]
Incase it may help, my phone's screen size is 6.44", 1080x2044

**Comment by sosauce** [comment]
That's a pretty large screen 🤔 I should start final testing on a real device ahah. Thanks for loving it !! ❤️

**Comment by sosauce** [comment]
Hello ! I hope you'll get this message, would you mind testing an early version of v2.2.2 ? My devices don't get the bug you get in landscape, so i have no idea if I actually fixed the issues or not

**Comment by quadroli** [comment]
Hello, I do not mind, in fact I can right away

**Comment by sosauce** [comment]
Thanks alot ! Beta avaible [here](https://github.com/sosauce/CuteCalc/releases/tag/v2.2.2_beta1)

**Comment by quadroli** [comment]
Perfect 👌
![Screenshot_20240122_192453](https://github.com/sosauce/CuteCalc/assets/58091631/4f82b55d-f928-4763-8d91-511e34d0f9dc)

**Comment by quadroli** [comment]
I suppose it shall make discussion easier 👍

**Comment by sosauce** [comment]
Indeed ahah ! Happy I managed to fixed that blindfolded
