### ISSUE TITLE
Request: Add parentheses (AVAIBLE IN 2.3)

### ISSUE THREAD

**Issue by quadroli** [sosauce/CuteCalc#17]
This will allow us to do such computations 60/(5-2) = 20 but as per now, its only possible to have 60/5-2 = 10

**Comment by sosauce** [comment]
Okay, update done [(here)](https://github.com/sosauce/CuteCalc/releases/tag/v2.3)

**Comment by quadroli** [comment]
Oof, new issue paren text is off in potrait mode
![Screenshot_20240123_155056](https://github.com/sosauce/CuteCalc/assets/58091631/0f4b1277-ef42-4734-9174-1e3132e7fe73)

**Comment by quadroli** [comment]
It also appears to be incomplete in landscape mode, like the bottom quater of the parenthesis aren't showing: 
![Screenshot_20240123_155352](https://github.com/sosauce/CuteCalc/assets/58091631/23b630ab-7073-4ee4-b3d0-4aecd3cf1013)

**Comment by sosauce** [comment]
NAURRRR 😭 okay fixing this right now

**Comment by quadroli** [comment]
But, Thank you for the functionality though 💪

**Comment by quadroli** [comment]
😂 that x.x.x scheme may still be useful for minor patches like these ...

**Comment by sosauce** [comment]
Oh yes ofc, i'll use 2.3.1 ahah, seemed logic for me, should of detailed !

**Comment by sosauce** [comment]
Should be fixed now [here](https://github.com/sosauce/CuteCalc/releases/tag/v2.3.1) 😔

**Comment by quadroli** [comment]
🥳 Wooww, lovee it! Kinda looks like a worm dancing 😂, defintely unique 🙌

**Comment by quadroli** [comment]
In landscape it still does chop off the bottom quater of ( 
but I'd take this ( potrait fixed ) over a bottom quater any day 🙏💪
Great work yoo! And speedy too 🏎️

**Comment by sosauce** [comment]
Might rewrite the full UI tbh lmaooo
I mean, I have nothing else todo, so I might aswell fix bugs 🏃

**Comment by sosauce** [comment]
Yooo, I think I found a way so the buttons don't look chopped anymore

**Comment by quadroli** [comment]
> Might rewrite the full UI tbh lmaooo I mean, I have nothing else todo, so I might aswell fix bugs 🏃

It does behave a bit weird tb frank

but, definitely made strides with these patches 💪

**Comment by quadroli** [comment]
> It does behave a bit weird tb frank

for example in split screen it goes bananas

![Screenshot_20240123_222017](https://github.com/sosauce/CuteCalc/assets/58091631/c6d43090-2979-4642-9b6f-d73c367d3be3)

![Screenshot_20240123_222035](https://github.com/sosauce/CuteCalc/assets/58091631/a6f45b5a-6285-4e13-8563-d45924c73105)

![Screenshot_20240123_222041](https://github.com/sosauce/CuteCalc/assets/58091631/c713848a-4653-4f58-a23d-415baed395d2)

![Screenshot_20240123_222053](https://github.com/sosauce/CuteCalc/assets/58091631/e77081d0-9b97-48a8-b921-fb7f318758a2)

**Comment by sosauce** [comment]
Oh wow, I don't know how to implement split screen..

**Comment by sosauce** [comment]
I think I've definitevely 100% fixed landscape mode for now 😅 Will push the update and wait for feedback!

**Comment by realeatham** [comment]
You should close this issue and make new issues for what you are discussing now.

**Comment by sosauce** [comment]
> You should close this issue and make new issues for what you are discussing now.

quadroli is like a tester for me, since he has issues I don't, so we talk about the here

**Comment by quadroli** [comment]
I can confirm that parenthesis is now drawing swell in both landscape and potrait 👌

**Comment by quadroli** [comment]
He does have a point though, for organisation opening a new issue is a good idea 👍
