### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by IzzySoft** [sosauce/CuteCalc#2]
Please remember to increase `versionCode` with each new release. This is used by Android internally to tell versions apart and decide whether to accept an APK as update. You currently list 3 releases here, yet the latest identifies as

    package: name='com.sosauce.cutecalc' versionCode='1' versionName='1.1.0'

Being the 3rd release, `versionCode` should at least be `3` at this point.

Thanks in advance for taking care!

**Comment by sosauce** [comment]
Hi ! Thanks for the feedback 😭  This went right through my radars lol. But now worries ! Should be fixed in version 1.2.0, wich is avaible to download right now !

**Comment by IzzySoft** [comment]
Cool, thanks! Then [this one](https://apt.izzysoft.de/packages/com.sosauce.cutecalc/) will be updated properly, wonderful!

**Comment by IzzySoft** [comment]
Looks like it didn't work out:

    Binary files /web/ftp/repo/fdroid/repo/com.sosauce.cutecalc_1.apk and /web/ftp/repo/fdroid/repo/com.sosauce.cutecalc_1.2.1.apk differ

which means v1.2.1 still has `versionCode: 1`. And so will the next release, unless you [update this](https://github.com/sosauce/CuteCalc/blob/main/app/build.gradle.kts#L14) :wink:

```gradle
    defaultConfig {
        applicationId = "com.sosauce.cutecalc"
        minSdk = 24
        targetSdk = 34
        versionCode = 1
        versionName = "1.2.0"
```

**Comment by sosauce** [comment]
Oof, my bad, didn't know I had to change that, releasing a fix ASAP

**Comment by sosauce** [comment]
I updated it, should be good. Do you need an APK the modification or not ?

**Comment by IzzySoft** [comment]
If the next release has it fixed, it should be fine. Just remember to increase it with *every* release. Also strange that `versionName` states `1.2.0`, while the last release says `1.2.1` – and the APK indeed has 1.2.1. Now I'm confused. Where do you set the "real version"?

**Comment by sosauce** [comment]
Sorry 😭 This is my first steps in Android dev, so i'm having a hard time with all that. But don't worry version 1.3.0 should have it all correctly :)

**Comment by IzzySoft** [comment]
No worries! I'm not even an Android developer at all, so you're ahead of me there :see_no_evil: Looking forward to the next update then :smiley:

**Comment by sosauce** [comment]
Update 1.3.0 avaible rn ! I changed the `versionCode` so should be all good ! also reduced app size by 2, if it can help ;)

**Comment by IzzySoft** [comment]
Thanks, that worked out fine now! :smiley: And yes, reducing the size is always a good thing, thanks!

Last question: would you like a PR with the app's metadata (description, graphics) in Fastlane format, so you can control how your app is presented? You're welcome to use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) as reference. It's basically just placing the corresponding text and graphic files into a directory structure, so no rocket science. Fastlane has established as quasi-standard for this.

**Comment by sosauce** [comment]
I'd be please to do that ! On on vacation right now without my laptop (Github mobile ykyk) So i'll see if I can do it on my phone, if not, it will be done after a come back (Jan 8) !

**Comment by IzzySoft** [comment]
Great! And no need to hurry things. First I need to make that PR – only after that it's for you to act. Basically, if you're happy with what you see, you can simply merge it (then I'd update the config here to check it whenever a new version of your app is pulled) – and adjust it whenever you have time and think it could use some improvements.

I'll prepare the PR then and leave some guiding notes with its opening comment, so you can easily find them.

**Comment by sosauce** [comment]
Oh okay ! Tell me when it's my turn ;)

**Comment by IzzySoft** [comment]
As I wrote: You can merge right away – which is the signal for me to enable it here. Then at any point you find time for it, you can improve it – e.g. expand the description, add more screenshots, add a featureGraphic, per-release changelogs if you wish… All at your own schedule.

**Comment by sosauce** [comment]
Ohhh okay, I merged itt

**Comment by IzzySoft** [comment]
Enabled it here. Now, everything else can be done whenever you decide :smiley:
