### ISSUE TITLE
cannot change theme

### ISSUE THREAD

**Issue by realeatham** [sosauce/CuteCalc#23]
https://github.com/sosauce/CuteCalc/assets/136866675/706a74f2-a1ab-47f6-b19c-d3f43787746a

**Comment by sosauce** [comment]
Yeah I know, i'm working on it rn i'm almost finished, should push the update in like less than an hour

**Comment by realeatham** [comment]
Ok

**Comment by realeatham** [comment]
Once it's done I am going to add more screenshots for the f-droid page

**Comment by sosauce** [comment]
Ok its avaible [here](https://github.com/sosauce/CuteCalc/releases/tag/v2.4)

**Comment by realeatham** [comment]
Thanks!
