### ISSUE TITLE
Haptic feedback on button press

### ISSUE THREAD

**Issue by realeatham** [sosauce/CuteCalc#24]
When you press a button, you get no vibration confirming you clicked it. This makes the app feel weird to use.

**Comment by sosauce** [comment]
Uhm, I'll look into it

**Comment by RudraOp9** [comment]
@ sosauce can i work on it.

**Comment by sosauce** [comment]
No need ahah, I'm already on it ^^

**Comment by sosauce** [comment]
Update avaible ^^
