### ISSUE TITLE
AMOLED mode should still have the colored circles around the buttons 

### ISSUE THREAD

**Issue by realeatham** [sosauce/CuteCalc#26]

**Comment by sosauce** [comment]
Do you want the buttons to be fully colored, or just the border ?

**Comment by realeatham** [comment]
Fully colored

**Comment by sosauce** [comment]
well uhm, the purpose of amoled is for all to be black to save power and amoled screen devices 😅

**Comment by realeatham** [comment]
I just use it because it looks nice. If it's not hard to do maybe the circles could just be an option

**Comment by sosauce** [comment]
good idea ! I'll look into it
