### ISSUE TITLE
UI Bug: Backspace button is off-center in portrait mode, and too big in landscape 

### ISSUE THREAD

**Issue by realeatham** [sosauce/CuteCalc#31]
**Describe the bug**
See images

**Screenshots**
![Screenshot_20240128_222105](https://github.com/sosauce/CuteCalc/assets/136866675/2681c918-258f-4707-b94b-f4705d010f9c)
![Screenshot_20240128_222059](https://github.com/sosauce/CuteCalc/assets/136866675/1b0fb55a-c5d4-43c0-afed-fc85283b39bf)

**Smartphone (please complete the following information):**
 - Device: S21
 - OS: OneUI 6/ Android 14 (do you want the android version or the OEM ROM version? Instruction unclear)
 - Version: App version 2.5

**Additional context**

**Comment by sosauce** [comment]
Okay will work on it, also note that OneUI is not an OS, just a skin, Android 14 is an OS 😉

**Comment by realeatham** [comment]
Ok thanks , Also I said the skin version on purpose as I wasn't sure which one you wanted.

**Comment by realeatham** [comment]
![Screenshot_20240218_102744](https://github.com/sosauce/CuteCalc/assets/136866675/fab6090f-5ad4-4427-ba52-6bd180b42152)
It got worse

**Comment by sosauce** [comment]
oof, I don't get this so it's hard for me to know if its fixed

**Comment by realeatham** [comment]
Ok. Could be related to the screen, font and zoom sizes maybe? I'll try different combinations.

**Comment by realeatham** [comment]
I can confirm it still happens with default and minimum settings let's you.(I use an app to lower it more)

**Comment by sosauce** [comment]
Maybe because its actually an image, I converted it back to text maybe it should solve the issue

If you wanna test on your device change to this : 

                    Button(
                        onClick = {
                            viewModel.handleAction(CalcAction.RemoveLast)
                            if (buttonVibrationEnabledState.value) {
                                vibration()
                            }
                        },
                        colors = ButtonDefaults.buttonColors(MaterialTheme.colorScheme.tertiaryContainer),
                        modifier = Modifier
                            .weight(0.15f)
                    ) {
                        Text(
                            text = "⌫",
                            color = MaterialTheme.colorScheme.onBackground,
                            fontSize = 35.sp,
                            fontFamily = GlobalFont,
                            modifier = Modifier.align(Alignment.CenterVertically)
                        )
                    }

**Comment by realeatham** [comment]
![Screenshot_20240218_222503](https://github.com/sosauce/CuteCalc/assets/136866675/8e6c0ea7-cfd8-42da-b6ed-c0525221fc9e)

It did not work at all

**Comment by realeatham** [comment]
The font does not support it

**Comment by realeatham** [comment]
I just checked Google fonts

**Comment by realeatham** [comment]
A separate font which supports this icon will have to be used for it only.

**Comment by realeatham** [comment]
Maybe the system font could be used?

**Comment by realeatham** [comment]
Segoe UI Symbol has a nice icon for it

**Comment by sosauce** [comment]
dang I was searching a font with a nice icon for it, others were ugly, thanks

**Comment by sosauce** [comment]
You have a S21 with a 6"1 1080 x 2400 screen right ? I'm gonna create an emulator with ur screen size to get a more accurate representation

**Comment by sosauce** [comment]
> ![Screenshot_20240218_222503](https://private-user-images.githubusercontent.com/136866675/305710582-8e6c0ea7-cfd8-42da-b6ed-c0525221fc9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNTgxNTYsIm5iZiI6MTcwODI1Nzg1NiwicGF0aCI6Ii8xMzY4NjY2NzUvMzA1NzEwNTgyLThlNmMwZWE3LWNmZDgtNDJkYS1iNmVkLWMwNTI1MjIxZmM5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOFQxMjA0MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNWFkNTYxZmI3MmQyOWFjY2Y4N2JlZGUwNmY0ZDEzNThiZDdiOThlYWI2NmQ5NWQ5NzA0MjQ3MzZlNmE3MDcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.acfZjBmLGR1nm_oqe8gOzI20Huzql-_zvDZNNVzv_yk)
> 
> It did not work at all

Also, the code snippet was for landscape layout ;) mb for not saying

**Comment by realeatham** [comment]
> You have a S21 with a 6"1 1080 x 2400 screen right ? I'm gonna create an emulator with ur screen size to get a more accurate representation

Probably, that's what Google said.

Keep in mind that I have screen zoom set to minimum and font size set to 0.6 using https://github.com/zacharee/Tweaker

**Comment by sosauce** [comment]
Ohhhh okay I see, that prolly influences some things. I'll keep in mind

**Comment by realeatham** [comment]
I did try it with default but it still happened, just less bad.

**Comment by sosauce** [comment]
I've changed it to a Text anyways, so it should scale like other buttons since they also use text

**Comment by sosauce** [comment]
Sorry was out, yes sure

**Comment by realeatham** [comment]
its fixed as of the latest github commits

**Comment by sosauce** [comment]
Okay, re open if needed
