### ISSUE TITLE
Better number order on landscape mode

### ISSUE THREAD

**Issue by realeatham** [sosauce/CuteCalc#33]
See image for how the number order should be.
![Screenshot_20240128_222727](https://github.com/sosauce/CuteCalc/assets/136866675/4148deb9-11fd-45b1-a12c-39807b6414dc)

**Comment by realeatham** [comment]
This is to make it similar to portrait mode and other calc apps

**Comment by sosauce** [comment]
Okay I will change

**Comment by realeatham** [comment]
i am fixing it now
