### ISSUE TITLE
UI Bug: Haptic Feedback not working in landscape mode

### ISSUE THREAD

**Issue by realeatham** [sosauce/CuteCalc#37]
**Describe the bug**
In landscape mode, haptic feedback does not work as its simply not implemented in LandscapeLayout.kt.

**Smartphone (please complete the following information):**
 - Device: S21
 - OS: Android 14
 - App Version: 2.5.1

**Additional context**
This seems like an easy fix so might do it myself

**Comment by sosauce** [comment]
Oops thats an oversight on my part
