### ISSUE TITLE
UI Bug: Haptic feedback too storng

### ISSUE THREAD

**Issue by realeatham** [sosauce/CuteCalc#38]
**Describe the bug**
When you press a button the vibration is too strong.

To fix, replace line 88 in Calculator.kt with the following:

`VibrationEffect.createOneShot(100, 90)`

Also, rename the setting from buttons vibrations to "Haptic Feedback"

**Comment by realeatham** [comment]
do the same in LandscapeLayout.kt on line 74

**Comment by sosauce** [comment]
Sorry I was a the therapist, okay I wil

**Comment by realeatham** [comment]
Can you commit it to GitHub?

**Comment by sosauce** [comment]
done
