### ISSUE TITLE
Rotation & UI Bug

### ISSUE THREAD

**Issue by KyuutePrincess** [sosauce/CuteCalc#4]
Weirdly when i rotate my phone the light theme turns back into the dark theme and the calculator buttons dont resize (i imagine landscape isnt implemented currently) 

also there is visual bug with the buttons
![475d0272-7811-4c78-b0ba-76099aaa6436.png](https://github.com/sosauce/CuteCalc/assets/131701519/bab9b56a-9e16-4727-bf1d-17b7ef4e696e)

I love the project idea btw as there are basically none cute open source apps so ill be following the project guaranteed!

**Comment by sosauce** [comment]
Hi! Thanks for the feeback! Landscape is indeed not implemented yet. What phone do you use on wich version of Android please ?

**Comment by KyuutePrincess** [comment]
No problem!

SM-G970F
PixelExperience_beyond0lte-13.0-20230714-0416-OFFICIAL

**Comment by sosauce** [comment]
Mhmm, your using a custom ROM I see, it may be why the buttons bug ? I've tested my app on 3 physical device and 1 virtual device and the buttons never bugged 🤔 Weird i'll search it !

**Comment by KyuutePrincess** [comment]
All right, thank you!

**Comment by sosauce** [comment]
Oh, it happens to my phone with a smaller screen. Will work on adaptive UI after my vacation !

**Comment by Shivamhobbyist** [comment]
> Mhmm, your using a custom ROM I see, it may be why the buttons bug ? I've tested my app on 3 physical device and 1 virtual device and the buttons never bugged 🤔 Weird i'll search it !

In my device also Galaxy a34 5G Android 14 One UI 6

**Comment by sosauce** [comment]
Weird, I think I messed up something in the latest update. Will fix when i come bach home !

**Comment by sosauce** [comment]
Fixed btw, forgot to tell you :)
