### ISSUE TITLE
Add History

### ISSUE THREAD

**Issue by quadroli** [sosauce/CuteCalc#40]
*Is your feature request related to a problem? Please describe.*

It would be nice if one could have history of at least the last 5 calculations, sometimes people like to go back to a calculation they did
or, this opens the possibility to use the calculator for briefly and quickly saving a number

*Describe the solution you'd like*

Add the ability to remember at least the last 5 previously done calculations, preferrably having them retained between sessions

*Describe alternatives you've considered*

Possibly saving the calculation in a note taking app if I may need it later

**Comment by realeatham** [comment]
Good idea

**Comment by sosauce** [comment]
Good idea indeed, will deffo look into it
