### ISSUE TITLE
Issue with Percentage Calculation

### ISSUE THREAD

**Issue by kamrulhasanio** [sosauce/CuteCalc#41]
**Describe the bug**
I encountered an issue when performing percentage calculations in Cute Calc.

**To Reproduce**
1. Open the Cute Calc app.
2. Input the following calculation: 500 - 20%
3. Observe the error or unexpected behavior.

**Expected behavior**
I expected the app to correctly calculate the result of 500 minus 20%.

**Screenshots**
https://github.com/sosauce/CuteCalc/assets/142052078/314a3c97-2b4b-40e5-88a5-00ca8e5f350f

**Smartphone:**
- Device: Redmi Note 12 4G
- OS: Android
- Version: 13

**Comment by quadroli** [comment]
Ah yess I remember being confised by yhis too, but that my friend is the modulo operator i.e. it gives you the remainder of an operation i.e. 10%3 = 1

See #15

**Comment by sosauce** [comment]
Yeah, the % is to calculate modulo, I should specifie it..

**Comment by realeatham** [comment]
Why not just switch it to percentage

**Comment by sosauce** [comment]
Because I'm using a math library (Keval). So I can't cuange what it does..

**Comment by realeatham** [comment]
Does keval have percentage at all?

**Comment by sosauce** [comment]
No, but % is used for remainders in math so I understand why not, maybe I could find a workaround since people don't seem to know about modulos..

**Comment by realeatham** [comment]
Can you give me a link to keval?

**Comment by sosauce** [comment]
https://github.com/notKamui/Keval

**Comment by realeatham** [comment]
You can definitely add percentage to that as it supports more operators and overriding preexisting operators.

**Comment by realeatham** [comment]
I might try later

**Comment by quadroli** [comment]
But that would mean coming up with a new symbol for it .. because mathematically both modulo and percentage are denoted by %

**Comment by quadroli** [comment]
And I'd argue modulo is more important because it's an operator .. but as for percentage, its just a different way to represent a no. i.e. 24% = 0.24 = 24/100

**Comment by realeatham** [comment]
You can just remove modulo, it's a scientific calc thing.

**Comment by realeatham** [comment]
Most people will want percentage

**Comment by sosauce** [comment]
Yeah, why have a button that is just a division. May just completely remove % button. Could use Keval{} to change the behavior but erh. Will test it but prolly will remove the % button

**Comment by sosauce** [comment]
Might replace with powers ? I've found myself needing powers way more then modulo/percentage espcially since the grade im in at school we used powers very often. Let me know what y'all find more usefull

**Comment by realeatham** [comment]
Yeah, exponents are a lot more useful. I did have an idea for how to have both in one button which we could use, but it's hard to describe, I'll make an animation to show it later maybe. But exponents is definitely more useful than percentage and modulo is basically useless.

**Comment by sosauce** [comment]
I've changed it to exponent, now just have to figure out how to add a cursor to the text (I have no idea how 💀)

**Comment by realeatham** [comment]
Ok. Don't forget to change landscape mode aswell.
