### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by saltsoftdrink** [sosauce/CuteCalc#42]
Can you please list all the resources by which you've created thi awesome app

**Comment by realeatham** [comment]
They used Kotlin with Android Studio most likely. Google has some good tutorials to learn Kotlin if want to.

**Comment by sosauce** [comment]
Yeah, Kotlin, Jetpack Compose, online tutorials, YouTube

**Comment by sosauce** [comment]
Im on vacation/break of too much coding (literally been doing only this for 2 months) so I don't have usefull website I could suggest atm
