### ISSUE TITLE
Allow user to move input cursor

### ISSUE THREAD

**Issue by quadroli** [sosauce/CuteCalc#43]
*Is your feature request related to a problem? Please describe.*

Currently, a user can only append i.e. input values to the end of the expression i.e. if I'm typying 1+4+7+8, I can only keep typing after 8 but let's say I mistook and actually wanted to type 6 instead of 4, now I have to delete all the way back to 1 so as to correct my mistake.

*Describe the solution you'd like*

I would like to tap where in the expression I'd like to add/modify input 

*Describe alternatives you've considered*

Currently I have to delete everything following the mistake so as to get to it.

*Additional context*

This change would make editing a mistake go from being an O(n) access problem to a O(1) access problem which is wayy more desirable 😁

**Comment by sosauce** [comment]
Idk why this isn't in the app yet 😞 Will 100% add it when im back from vacation ;)

**Comment by quadroli** [comment]
Awesome 🙏

**Comment by sosauce** [comment]
Okay, so this was meant to be in v3, but Google did some LAST MINUTE CHANGES WHICH LITERALLY BROKE THE FEATURE !!!
