### ISSUE TITLE
Simplify Number 

### ISSUE THREAD

**Issue by saltsoftdrink** [sosauce/CuteCalc#46]
Add custom comma in numbers in different format like USA and India

**Comment by sosauce** [comment]
Noted ✏️...

**Comment by realeatham** [comment]
is this commited yet? im not seeing it

**Comment by sosauce** [comment]
Should be yeah

**Comment by sosauce** [comment]
Update up!

**Comment by saltsoftdrink** [comment]
> Update up!

Add Indian decimal format in that

**Comment by sosauce** [comment]
Mhmm, okay I will

**Comment by saltsoftdrink** [comment]
> Mhmm, okay I will

They are like there is comma before three no. first time and rest off it comma before 2 no.

Example :-
India - 10,00,00,00,000
Foreign - 10,000,000,000

**Comment by realeatham** [comment]
Also add Australia: 100 000 000
Same as most but instead of comma it's a space. Most Aussies don't use it but it's the official govt way and it looks nicer than comma.
There should also be a drop-down menu instead of a switch, with the default being no formatting

**Comment by realeatham** [comment]
And haptics should be on by default

**Comment by sosauce** [comment]
I don't agree with haptics, most devices (at least all the one I tested/have) have haptics turned off by default

**Comment by sosauce** [comment]
It's 1 switch away cmon 😅😭

**Comment by realeatham** [comment]
I have to reinstall the app every time a new release happens or I load it from my computer and it's annoying. Doesn't really matter. You should add Australian number format

**Comment by sosauce** [comment]
Why do you have to re install ?

**Comment by realeatham** [comment]
When I load from a computer it is not signed but when I use an APK it is, so they are incompatible. I don't think there is a way to bypass this.

**Comment by sosauce** [comment]
Maybe when you load on the computer your loading the debug version

**Comment by realeatham** [comment]
I mean when my computer complies it. It's because of a security feature which cannot be disabled, and even if it could I would not.
