### ISSUE TITLE
Dynamic Color

### ISSUE THREAD

**Issue by saltsoftdrink** [sosauce/CuteCalc#47]
Can you add this different particular colors - https://ibb.co/BLF5k0Q

This is from Seal (FOSS) App available on GitHub

This feature will be useful in designing part just add the library

**Comment by sosauce** [comment]
Im not quiet sure what do you mean by that 🤔 the app uses material 3 so it should use the color palette you choose 🤔

**Comment by saltsoftdrink** [comment]
> Im not quiet sure what do you mean by that 🤔 the app uses material 3 so it should use the color palette you choose 🤔

The app should provide a particular palatte as shown in img, so I can easily change between different colours

**Comment by sosauce** [comment]
Oh i see, erm, i don't know how todo that...

**Comment by sosauce** [comment]
?
