### ISSUE TITLE
[Logic Bug] com.notkamui.libs:keval issue

### ISSUE THREAD

**Issue by Artem13327** [sosauce/CuteCalc#49]
There is such an interesting thing https://github.com/notKamui/Keval/issues/35.

**Comment by sosauce** [comment]
Yeah, I can't do much about it. Im gonna ask him if he's on it

**Comment by realeatham** [comment]
for that there would need to be another completly compatible libary, which i doubt has been made.

**Comment by sosauce** [comment]
Yeah, i searched with no success

**Comment by notKamui** [comment]
@sosauce the new 1.0.0 release now supports unary operators ! (watch out for some breaking changes)

**Comment by sosauce** [comment]
Cool tuank you smmm, will test tmrw !
