### ISSUE TITLE
Rules of maths

### ISSUE THREAD

**Issue by Der-Flip** [sosauce/CuteCalc#5]
First of all: you are doing great here especially considering how young you are! It is indeed a cute looking calculator!

One thing you should tend to fairly soon-ish is the priority if the math operators. 1+2*3 shouldn't result in 9 but in 7.

Do it in your time but it is something you should keep in mind :)

**Comment by sosauce** [comment]
Ah yes ! PEMDAS, a classic we can't escape ! I'll look into it when I come back from vacations :) For now im noting every issues i'm getting. Thanks for the feedback !

**Comment by sosauce** [comment]
Heya, fixed in [version 2](https://github.com/sosauce/CuteCalc/releases/tag/v.2.0.0) :)
