### ISSUE TITLE
Splash screen on Android 11 is still here

### ISSUE THREAD

**Issue by Artem13327** [sosauce/CuteCalc#51]
I understand you forgot to remove the dependency with it

**Comment by sosauce** [comment]
Yeah cuz if I remove it, the spalsh screen will be all white wich isn't pleasing lemme check

**Comment by sosauce** [comment]
https://github.com/sosauce/CuteCalc/assets/98750531/561daf2d-23c9-4571-ab60-cec3a61b2196

see what i mean ?

**Comment by sosauce** [comment]
Oh yeah now I removed the dependency, send the pull request when ur done

**Comment by sosauce** [comment]
Okay, I'll add back what I have but with an if/else that checks if ur on A12 or lower
