### ISSUE TITLE
.gradle and .idea directories

### ISSUE THREAD

**Issue by notKamui** [sosauce/CuteCalc#56]
the `.gradle` and `.idea` folders shouldn't be committed, except for some files, sometimes, in the .idea folder, when you want every contributor to use the same IDE settings as you (which you don't want most of the time)

but the worst contender here really is the `.gradle` directory: it contains gradle cached files and compiled things. it has nothing to do with the source code.

this is very obvious in EVERY commits you're doing: your commits are always poluted with files which have nothing to do with the semantic role of said commits.

**Comment by sosauce** [comment]
oof okay I'll add to gitignore
