### ISSUE TITLE
Small recommendations

### ISSUE THREAD

**Issue by Artem13327** [sosauce/CuteCalc#57]
Please do not combine changes made before and after the release of the new version into one commit.
For example: you have already compiled a new release and made a change that was not included in it, publish this change after the release and its source code is published
This confused me in the commit https://github.com/sosauce/CuteCalc/commit/787c66ed5d841cfaf76a402e60eab186c3156a14

**Comment by sosauce** [comment]
Yeah I didn't mean to commit sorry lol
