### ISSUE TITLE
release tags don't match APKs

### ISSUE THREAD

**Issue by obfusk** [sosauce/CuteCalc#58]
Hi! It looks like your last 3 releases (which is all I checked) have a tag that's (at least) one commit behind the commit the APK was actually built from. So anyone building from e.g. tag `v2.6` would get a completely different APK (with the version code/name of the previous release and possibly missing other changes) than the one published with that release.

**Comment by realeatham** [comment]
It goes further than the last 3 in general commits arrive late

**Comment by sosauce** [comment]
I keep pushing randomly at time I shouldn't I know 😅

**Comment by realeatham** [comment]
Make sure you always have everything pushed before releasing an update

**Comment by sosauce** [comment]
I always do and I'm starting to suspect that GitHub hates me

**Comment by obfusk** [comment]
The latest release APK does now indeed match the tag, except for one part: `META-INF/version-control-info.textproto` contains the commit hash f00fe1c3481538787d2626f9bfe944f252d28d51 (an older commit, presumably because you built the APK before committing the changes) instead of bb85e8b8bf7d32dba8c40744ff050489894143b0 (the commit hash for tag `v2.7.1`, which is what anyone cloning the repo and then building from the tag will get).
