### ISSUE TITLE
Add minSDK21, support from Android_5, please!

### ISSUE THREAD

**Issue by DI555** [sosauce/CuteCalc#67]
Please, add minSDK21, or at least minSDK22!!!
We have a lot of Android_5 cute devices to work on them!
Many thanks in advance!

**Comment by realeatham** [comment]
That would prevent it from being installed on new android versions due to stupid policies. I guess multiple apks could be compiled?

**Comment by realeatham** [comment]
Hopefully if @sosauce considers this they make sure that every version since minimum the app supports will work (i.e. latest android allows sdk24 or above, so the other release would be the minsdk for whatever version is sdk23

**Comment by realeatham** [comment]
Obviously at a point the functions used by the app will not be supported by an android version so that can be the minimum

**Comment by sosauce** [comment]
Hello, will try to add support ! But it may be impossible due to some limitations (i.e. some piece of code being able to be only executed on Android version x and up) but I can try to find an adjustement 😄

**Comment by sosauce** [comment]
Quick update, after reading Android 15 documentation (It shouls be avaible in august so i'd rather focus on it than Android 14), it seems that its more the targetSDK that is needed to get bumped https://developer.android.com/about/versions/15/behavior-changes-all#minimum-target-api-level

I've bumped down minSDK to 21 and it runs fine on my Andorid 14 !
