### ISSUE TITLE
Make pop-out bg a little darker on dark mode

### ISSUE THREAD

**Issue by rickdtc** [sosauce/CuteCalc#7]
It would be great if this bg color here could be a little darker :  

![Screenshot_20240110_101249](https://github.com/sosauce/CuteCalc/assets/74096544/56231e3e-ef72-49c6-bcb6-f9d34ab5d705)

Great app tho, eagerly waiting whatever you are cooking!

**Comment by sosauce** [comment]
Hello !Thank you for using my app :) Will be fixed in next update!

**Comment by rickdtc** [comment]
Ight thanks let's go

**Comment by rickdtc** [comment]
Can I close this issue? as this was implemented in [Version 1.5.0](https://github.com/sosauce/CuteCalc/releases/tag/v.1.5.0)

**Comment by sosauce** [comment]
Yesss ;) I'll do it
