### ISSUE TITLE
Sort history from newest to oldest i.e. newest as the top

### ISSUE THREAD

**Issue by quadroli** [sosauce/CuteCalc#70]
*Is your feature request related to a problem? Please describe.*
Yes, it is, more often than not, the calculation I'm interested in is the most recent, hence I would prefer having it at the top of the list instead

*Describe the solution you'd like*
Have history sorted from newest to oldest

*Describe alternatives you've considered*
Having to scroll all the way down 🥲

**Comment by quadroli** [comment]
Also, long time Sosauce, glad to see you got history working 👏👏 cleeeaann!

**Comment by quadroli** [comment]
PS: I already made it my default Calculator 😁 (after the history update)

**Comment by sosauce** [comment]
Ohhh now that I'm thinking about it, this didn't happen during testing, probably an easy bug fix !

**Comment by quadroli** [comment]
Oof. I think you did the opposite 😅 I was requesting for newest at the top 😅 they are often more relevant than older claculations ..

**Comment by sosauce** [comment]
Ohhh are the calculation you did before 3.1.0 still from old to new ? I think that's because of how the database (Room) works, I need to investigate 🤔

**Comment by sosauce** [comment]
I'll try adding a sort button !

**Comment by quadroli** [comment]
@sosauce sorry, I'm still on version 3.0.0
