### ISSUE TITLE
Change pi from the word to the symbol in the calculation input

### ISSUE THREAD

**Issue by realeatham** [sosauce/CuteCalc#71]
**Is your feature request related to a problem? Please describe.**
There is no reason to have it as the letters when the button is the symbol

**Describe the solution you'd like**
Make it use the symbol instead of "Pi"

**Describe alternatives you've considered**
No
**Additional context**

**Comment by sosauce** [comment]
I actual tried that, but I got weird crashes, due to utf-8 encoding errors ??? I'll fix it no probs
