### ISSUE TITLE
Logic Bug: error when Doing Pi5²

### ISSUE THREAD

**Issue by realeatham** [sosauce/CuteCalc#72]
**Describe the bug**
When doing Pi 5 squared it says error with no further context. πr² is a basic formula which for some reason errors out I can't think of why.

**To Reproduce**

https://github.com/user-attachments/assets/b7a2c787-afaf-4785-853d-c1530f15773b

**Expected behavior**
It should return 78.53981633974483

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Galaxy S21
 - OS: OneUI 6 based on android 14
 - Version: 3.0.0

**Additional context**

**Comment by realeatham** [comment]
Just checked and yetcalc returns NaN, which is even werider.

**Comment by sosauce** [comment]
mhmmm weird shenanigans gong on here 🤔

**Comment by notKamui** [comment]
Nothing weird at all, PI5 is interpreted as is. The intepreter will search for a symbol (constant) named `PI5` which doesn't exist.

`PI * 5^2` is the correct way to write it. `PI 5^2` will also probably work but it looks dumb.

**Comment by realeatham** [comment]
I know that can be done, but π5²  is still correct math, as  * is implied.

**Comment by sosauce** [comment]
Re-open this if needed

**Comment by realeatham** [comment]
I checked my real calculators and they accept it

**Comment by realeatham** [comment]
However if it is too much work don't bother, as it can be done backwards

**Comment by sosauce** [comment]
I mean, if notKamui agrees on it not being an issue then I agress too 🤷

**Comment by notKamui** [comment]
I mean, if you want π5 to work as PI*5, you can just replace π with `PI ` (blank space included) before passing it to Keval, and it will work

**Comment by notKamui** [comment]
<img width="580" alt="Screenshot 2024-10-08 at 11 07 58 AM" src="https://github.com/user-attachments/assets/71fdea61-0e26-4607-9e38-8f3e6a329d4b">
<img width="166" alt="Screenshot 2024-10-08 at 11 08 05 AM" src="https://github.com/user-attachments/assets/43ca8f59-3a39-46ba-81c1-cfc66e1dd5ba">

**Comment by notKamui** [comment]
Dont replace `π` with `PI*` though, because it will break expressions such as `π+2` which will expand to `PI*+2` which is not valid

**Comment by sosauce** [comment]
Meh, too much for so less, I'll keep it as is
