### ISSUE TITLE
v3.1.0 release isn't marked latest

### ISSUE THREAD

**Issue by obfusk** [sosauce/CuteCalc#73]
v3.0.0 is still marked latest, which means v3.1.0 won't be picked up for [Reproducible Builds](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients) verification for IzzyOnDroid. Is that intentional?

![image](https://github.com/user-attachments/assets/4aad244e-d3b5-4e76-bb6b-21cb2a17faab)

cc @IzzySoft

**Comment by obfusk** [comment]
Thanks! v3.1.0 is now confirmed to be reproducible :tada:

**Comment by IzzySoft** [comment]
Thanks to both of you! So with tomorrow's sync, v3.1.0 should show up at IoD (I just made sure of that – due to a typo on my end in the config file, v3.0.0 was not picked up unfortunately, which is fixed now) – hopefully with the green RB shield again!
