### ISSUE TITLE
Cursor behaviour is weird

### ISSUE THREAD

**Issue by quadroli** [sosauce/CuteCalc#75]
**Describe the bug**
The cursor does not input characters where intended and takes itself to the front

**To Reproduce**
As shown in the attached video

**Expected behavior**
Digits to be placed where the cursor is and the cursor not to automatically go to the front.

**Screenshots**
https://github.com/user-attachments/assets/be85f0c2-9a71-4ae3-9c6d-a5ff74e771d9

**Smartphone (please complete the following information):**
 - Device: vivo device
 - OS: Android 12
 - Version: Funtouch OS 12

**Additional Context**
Awesome work finally getting around this 🥳

**Comment by sosauce** [comment]
I kinda expected something like this, I had to use a weird workaround cuz Google deprecating stuff 😒
