### ISSUE TITLE
Starting with a . results in an error

### ISSUE THREAD

**Issue by quadroli** [sosauce/CuteCalc#76]
**Describe the bug**
Starting with a . without a leading zero always results in an error even though the expression is correct

**To Reproduce**
Type in the expression 0.5+.7

**Expected behavior**
Valid expressions not to be treated as errors

**Screenshots**
![Screenshot_20241010_205743](https://github.com/user-attachments/assets/1ed93c12-b1d5-4c43-8aab-c273f66dd60d)

![Screenshot_20241010_205758](https://github.com/user-attachments/assets/b410cd14-3fd5-4f55-a88e-8b8534f25c81)

![Screenshot_20241010_205827](https://github.com/user-attachments/assets/499983c6-455c-4070-bd18-1ec8f5ac2572)

**Smartphone (please complete the following information):**
 - Device: Vivo device
 - OS: Android 12
 - Version: Funtouch OS 12

**Additional context**
Good work on taking care of the cursor issue 😁

**Comment by sosauce** [comment]
Yeah, notKamui already said he's not implementing that, and in my opinion its not really a good practice, at least for me !

**Comment by quadroli** [comment]
Fair enough,
bu' @notKamui do consider 😁

**Comment by notKamui** [comment]
Hello @quadroli 
As said in the other issue, I will not support non-standard notation.
This decision is especially valid in my opinion because it would be very easy for @sosauce to add that feature themselves by pretreating the input by adding a 0 before every dot if there is no digit before it.

**Comment by realeatham** [comment]
Isn't standard notation referring to numbers like 7856 rather than scientific notation? Don't think the decimal point can't be at the front there (although I don't care whether or not you implement it in keval, just clarifying what you mean by standard notation)

**Comment by notKamui** [comment]
Not really, but you're right in that I should clarify. Scientific notation belongs to a standard (and you can actually implement it using custom operators or functions in Keval). By "non-standard" I mean notation that is not correct everywhere in the world.
In the case of the decimal point being at the front without a leading 0, it is very American, so not standard.
