### ISSUE TITLE
Add App Signing Certificate SHA-256 Hash to README

### ISSUE THREAD

**Issue by NarwhalPrince** [sosauce/CuteCalc#77]
I would like to request that the app signing certificate SHA-256 hash be added to the GitHub README for this project. This would greatly assist with verifying the authenticity of APKs downloaded from non-trusted sources, such as directly from GitHub or other websites, compared to trusted sources like the Google Play Store or Accrescent.

By including this information, users can easily use tools like [AppVerifier](https://github.com/soupslurpr/AppVerifier) to confirm the APK's authenticity before installation.

Thank you for considering this request!

**Comment by NarwhalPrince** [comment]
Hey! Thanks for doing that. It doesn't look like it matches what I'm getting. 
Can you try using the apksigner tool with the --print-certs option https://developer.android.com/tools/apksigner#usage-verify


Also, is there anywhere else (e.g. a website) where you can have the hash posted? 

The use case for this isn't for apps hosted on the Play Store, it is for obtaining apps from sources without a chain of trust. This allows us to mitigate issues with trust on first use (TOFU).

**Comment by sosauce** [comment]
Signer #1 certificate SHA-256 digest: fd2d95cdb348b2f1aebedbab879ced737385ee13c305a139d6580d4cf2c0d65a

This is what I got with apksigner, is this what you also get ? I have my website : https://sosauce.github.io/  Would it be okay to put the keys here ?

**Comment by NarwhalPrince** [comment]
Yes and yes! 

APK fingerprint matches and posted to your website would be best. You can just link to the page where the hash is placed.

![Screenshot_20241011-130054.png](https://github.com/user-attachments/assets/2cf3d530-77e3-4666-ad8b-1b36816a0078)

**Comment by sosauce** [comment]
Great, will do ASAP!

**Comment by sosauce** [comment]
Hi again ! I've added the SHA-265 to my website here : https://sosauce.github.io/projects/
Hash given by apksigner so it should be all good now !

**Comment by NarwhalPrince** [comment]
Awesome, thank you!

**Comment by realeatham** [comment]
@DI555 why would it do that? The signing key is the same.

**Comment by realeatham** [comment]
Also there are 4 options I don't think it matters if you have to reset them

**Comment by sosauce** [comment]
The apk's are all signed with the same keystore so it should stay the same

**Comment by sosauce** [comment]
History is saved in the app's data storage, as long as you don't clear / uninstall the app it stays here !!
