### ISSUE TITLE
UI Bug - Cursor starts typing at the start of numbers entered from an expression.

### ISSUE THREAD

**Issue by ChrisDeardeuff** [sosauce/CuteCalc#78]
**Describe the bug**
When you perform an expression (let's say 1+2) and hit enter, the value is displayed (3). But if you start typing (let's say to do 3*8), the cursor is on the far left when it should be on the far right (it will look like this *83).

**Screenshots**

![Screenshot_20241017-114426.png](https://github.com/user-attachments/assets/b8ad04cc-6b16-4515-a306-190cf16da439)

![Screenshot_20241017-114431.png](https://github.com/user-attachments/assets/4826187d-3ea2-4b2f-a485-4973ff3df2c3)

![Screenshot_20241017-114436.png](https://github.com/user-attachments/assets/f590028b-e0bd-41ba-8d19-722a58505a86)

1. 3+2
2. Hit enter
3. *6

**Smartphone (please complete the following information):**
 - Device: Pixel Fold
 - OS: GrapheneOS
 - Version: 14

**Additional context**
The images might be out of order, my apologies. I am filling this from mobile and the previews were hard to see.

**Comment by realeatham** [comment]
I can confirm this happens
