### ISSUE TITLE
[REQ] Memory buttons 

### ISSUE THREAD

**Issue by sanctimoniousape** [sosauce/CuteCalc#8]
As an initial step towards that daunting scientific mode in your roadmap, may I request that you implement the memory buttons found on virtually all common real-world calculators? I find this feature essential in my basic day-to-day usage.

In case you're unfamiliar with what I'm referring to, here's a description of a typical four-button arrangement (there are other similar arrangements if you prefer, it's the function itself that matters to me), taken from [this page](https://www.ni.com/docs/en-US/bundle/diadem/page/dlgcalculator/dlgcalculator/dlgcalculation_buttons.htm):

> Use the MC (Memory clear) button to delete the contents of the intermediate memory.

>Use the MR (Memory recall) button to enter the contents of the intermediate memory into the text box.

>Use the M+ (Memory +) button to add the result of the current calculation to the contents of the buffer.

>Use the M- (Memory -) button to subtract the result of the current calculation from the contents of the buffer.

Thanks for you time & donating your programming skills to the benefit of all.  I wish you much luck in your future career!

**Comment by sosauce** [comment]
Hello! Thanks for the request, I'd like to add that ! But I read what you sent but can't understand what does these buttons actually do (i am dumb) 😭

**Comment by sosauce** [comment]
Because I think they delete what's in the memory, but the app doesn't store anything in memory, once you press "AC", all content is ereased, if this makes sense

**Comment by sanctimoniousape** [comment]
Depends upon how the calculator is designed, but that's generally why there's an AC button to begin with: there's usually also a C button that doesn't affect the memory store.  Other implementations have an MC button to specifically handle the memory store separately. Whatever style you prefer is fine.

BTW, not knowing something doesn't make you "dumb" if you've never had reason to know it before. There's a big difference between not having experience with something versus having the experience, and not learning from it. I'm assuming the former is the case for someone your age, so please stop being so hard on yourself!

Thanks for the rapid reply, and for considering my request.

**Comment by sosauce** [comment]
No problem ! Because the app doesn't store anything in memory, a MC button would do nothing I think 🤔 So i'll prolly not add one..
