### ISSUE TITLE
Request: Change font

### ISSUE THREAD

**Issue by haunt98** [sosauce/CuteCalc#9]
Can I change to a cute font? Just like the name cute calc?

**Comment by sosauce** [comment]
Hello! I was thinking about that indeed ! Will search for a cute font, and implement it in version 1.5.1 ;)

**Comment by sosauce** [comment]
Do you have a suggestion ? Cuz im gonna prolly use something rounded

**Comment by haunt98** [comment]
Hi @sosauce, miss the question but I see you already have the cute font in mind. Good change!
